### PR TITLE
Organized screens into seperate files

### PR DESCRIPTION
**Pull request by Yunseo-Han**
Moved budgetListScreen and budgetScreen out of App.js and into seperate files. App.js now imports the screen to use it.

### CODE REVIEW

**Review by valesalh — APPROVED** [review]
Good work.

**Review by AbdulBasitA — COMMENTED** [review]
Looks good!

**Comment by AbdulBasitA** [comment]
Approved

**Review by AbdulBasitA — APPROVED** [review]
Approved

**Review by AshleyEmily — APPROVED** [review]
Nice

**Pull request merged**
