### PR TITLE
Budr 1

### PR DESCRIPTION
**Pull request by Yunseo-Han**
Cleaned up UI, added edit budget modal.

### CODE REVIEW

**Review by AbdulBasitA — APPROVED** [review]
Looks good!

**Review by valesalh — APPROVED** [review]
Yay good job

**Review by AbdulBasitA — APPROVED** [review]
Looks good!

**Review by AbdulBasitA — APPROVED** [review]
Looks good!

**Review by AshleyEmily — APPROVED** [review]
Looks cool babe

**Pull request merged**
