### PR TITLE
Bud 4

### PR DESCRIPTION
**Pull request by AshleyEmily**
Front-end, Organized code into pages 
New page: BudgetScreen

### CODE REVIEW

**Comment by Yunseo-Han** [comment]
Looks great! We should organize the views into separate files to keep the code organized.

**Review by valesalh — APPROVED** [review]
Nice!

**Review by Yunseo-Han — APPROVED** [review]
Looks great! We should organize the views into separate files to keep the code organized.

**Review by AbdulBasitA — COMMENTED** [review]
LG! Approved.

**Pull request merged**
