### PR TITLE
Partial implementation of budgets front end

### PR DESCRIPTION
**Pull request by Yunseo-Han**
Please code review

### CODE REVIEW

**Comment by AbdulBasitA** [comment]
Looks good! Clean UI, organized code. Good work!

**Comment by valesalh** [comment]
Looks good.

**Review by valesalh — APPROVED** [review]
Approved.

**Comment by AshleyEmily** [comment]
Great code, very clean

**Review by AshleyEmily — APPROVED** [review]

**Review by AbdulBasitA — APPROVED** [review]
Good work! UI code looks clean.

**Pull request merged**
